/*
 * Defaults internos usados quando a aplicação não fornece valores explícitos.
 */

#ifndef L2TAP_SNIFFER_DEFAULTS_H
#define L2TAP_SNIFFER_DEFAULTS_H

#include "sdkconfig.h"

#ifndef CONFIG_EXAMPLE_SNIFFER_PAYLOAD_PREVIEW_BYTES
#define CONFIG_EXAMPLE_SNIFFER_PAYLOAD_PREVIEW_BYTES 32
#endif

#ifndef CONFIG_EXAMPLE_SNIFFER_MAX_FRAME_LEN
#define CONFIG_EXAMPLE_SNIFFER_MAX_FRAME_LEN 1600
#endif

#ifndef CONFIG_EXAMPLE_SNIFFER_STATS_PERIOD_MS
#define CONFIG_EXAMPLE_SNIFFER_STATS_PERIOD_MS 5000
#endif

#ifndef CONFIG_EXAMPLE_SNIFFER_RING_BUFFER_SIZE
#define CONFIG_EXAMPLE_SNIFFER_RING_BUFFER_SIZE 16384
#endif

#ifndef CONFIG_EXAMPLE_SNIFFER_ETH_POWER_UP_DELAY_MS
#define CONFIG_EXAMPLE_SNIFFER_ETH_POWER_UP_DELAY_MS 100
#endif

#ifndef CONFIG_EXAMPLE_SNIFFER_ETH_LINK_UP_TIMEOUT_MS
#define CONFIG_EXAMPLE_SNIFFER_ETH_LINK_UP_TIMEOUT_MS 15000
#endif

#ifndef CONFIG_ESP_NETIF_L2_TAP_MAX_FDS
#define CONFIG_ESP_NETIF_L2_TAP_MAX_FDS 6
#endif

#define L2TAP_SNIFFER_TAG                         "l2tap_sniffer"
#define L2TAP_SNIFFER_DEFAULT_INTERFACE_NAME      "ETH_DEF"
#define L2TAP_SNIFFER_INVALID_FD                  -1
#define L2TAP_SNIFFER_MAC_ADDR_LEN                6

#define L2TAP_SNIFFER_CAPTURE_TASK_STACK_SIZE     4096
#define L2TAP_SNIFFER_ANALYZER_TASK_STACK_SIZE    6144
#define L2TAP_SNIFFER_STATS_TASK_STACK_SIZE       3072

#define L2TAP_SNIFFER_CAPTURE_TASK_PRIORITY       6
#define L2TAP_SNIFFER_ANALYZER_TASK_PRIORITY      7
#define L2TAP_SNIFFER_STATS_TASK_PRIORITY         3

#define L2TAP_SNIFFER_ANALYZER_WAIT_MS            100
#define L2TAP_SNIFFER_TASK_JOIN_WAIT_MS           1000

#define L2TAP_SNIFFER_INDUSTRIAL_PORT_MODBUS_TCP  502
#define L2TAP_SNIFFER_INDUSTRIAL_PORT_ETHERNET_IP 44818

#endif
